### ISSUE TITLE
[dispatch] handle: failed to parse S_START_FISHING_CHARGE

### ISSUE THREAD

**Issue by ChicknWing** [SoliaRdi/auto-fishing#2]
[dispatch] handle: failed to parse S_START_FISHING_CHARGE<1>
hook: (anonymous) in auto-fishing-master
data: 09008fff0181270300
error: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:27)
    at Readable.uint64 (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\stream.js:41:22)
    at parseField (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\index.js:425:37)
    at TeraProtocol.parse (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\index.js:434:7)

**Comment by SoliaRdi** [comment]
which region?

**Comment by ChicknWing** [comment]
NA

**Comment by teraoo** [comment]
Have you op codes for Eu?

**Comment by ChicknWing** [comment]
No, sorry.

**Comment by teraoo** [comment]
any good op code logger/finder

**Comment by ChicknWing** [comment]
I use https://github.com/Owyn/alex-packet-id-finder

**Comment by teraoo** [comment]
ty

**Comment by SoliaRdi** [comment]
should be fixed. i rename to S_FISHING_BITE

**Comment by ChicknWing** [comment]
I'm still getting an error. 

[dispatch] handle: failed to parse S_FISHING_BITE<1>
hook: (anonymous) in auto-fishing
data: 09008fff0181270300
error: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:27)
    at Readable.uint64 (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\stream.js:41:22)
    at parseField (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\index.js:425:37)
    at TeraProtocol.parse (C:\tera-proxy\node_modules\tera-data-parser\lib\protocol\index.js:434:7)

**Comment by SoliaRdi** [comment]
this opcode much more longer. Like

**Comment by ChicknWing** [comment]
Changed opcode to S_FISHING_BITE = 23837
Working now. Thanks for the awesome mod!  <3
